#!/bin/bash
set -e

# Проверяем, установлена ли Grafana
if ! dpkg -s grafana >/dev/null 2>&1; then
    echo "=== [A.I.S.B.E.R.G.] Шаг 1: Подготовка Grafana... ==="
    
    # Просто скачиваем файл. wget не блокирует базу пакетов.
    wget -q --show-progress -O /tmp/grafana_10.4.2_amd64.deb \
    https://dl.grafana.com/oss/release/grafana_10.4.2_amd64.deb || {
        echo "Ошибка: Не удалось скачать Grafana"
        exit 1
    }
    echo "=== [A.I.S.B.E.R.G.] Файл скачан в /tmp. Установка будет выполнена позже. ==="
else
    echo "=== [A.I.S.B.E.R.G.] Grafana уже присутствует в системе. === "
fi

exit 0
