#!/bin/bash
set -e

. /usr/share/debconf/confmodule

db_get aisberg/role || true
ROLE="${RET:-CLOUD}"

if [ "$ROLE" = "Server" ]; then
    if ! dpkg -s grafana >/dev/null 2>&1; then
        echo "=== [A.I.S.B.E.R.G.] Роль SERVER: Подготовка Grafana 11.x... ==="
        # Скачиваем 11-ю версию
        if [ ! -f /tmp/grafana_11.0.0_amd64.deb ]; then
            wget -q --show-progress -O /tmp/grafana_11.0.0_amd64.deb \
            https://dl.grafana.com/oss/release/grafana_11.0.0_amd64.deb || exit 1
        fi
        echo "=== [A.I.S.B.E.R.G.] Пакет Grafana 11.0.0 скачан в /tmp. ==="
    fi
else
    echo "=== [A.I.S.B.E.R.G.] Роль CLOUD: Пропуск скачивания Grafana. ==="
fi

exit 0
